# Projet Analyse de Données : Segmentation des pays

# --------------------------------------------------------------------------------------------

Dans le cadre de notre projet, nous allons faire une segmentation des pays en un ensemble de clusters. Pour cela, nous allons fusionner 4 ensembles de données (datasets) distincts, chacun fournissant des informations spécifiques sur les pays du monde. Les ensembles de données concernent les domaines de l'énergie, de l'armée, de la population et des données générales sur les pays.

In [1]:
#importation des librairies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1/ Lire les datasets

In [2]:
#On lit les 4 datasets

df1 = pd.read_csv("Country-data.csv")
df2 = pd.read_csv("energy.csv")
df3 = pd.read_csv("population.csv")
df4 = pd.read_csv("firepower.csv")

Premier dataset : Données générales sur les pays

In [3]:
df1

,country,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp
0,Afghanistan,90.2,10.0,7.58,44.9,1610,9.44,56.2,5.82,553
1,Albania,16.6,28.0,6.55,48.6,9930,4.49,76.3,1.65,4090
2,Algeria,27.3,38.4,4.17,31.4,12900,16.10,76.5,2.89,4460
3,Angola,119.0,62.3,2.85,42.9,5900,22.40,60.1,6.16,3530
4,Antigua and Barbuda,10.3,45.5,6.03,58.9,19100,1.44,76.8,2.13,12200
...,...,...,...,...,...,...,...,...,...,...
162,Vanuatu,29.2,46.6,5.25,52.7,2950,2.62,63.0,3.50,2970
163,Venezuela,17.1,28.5,4.91,17.6,16500,45.90,75.4,2.47,13500
164,Vietnam,23.3,72.0,6.84,80.2,4490,12.10,73.1,1.95,1310
165,Yemen,56.3,30.0,5.18,34.4,4480,23.60,67.5,4.67,1310
166,Zambia,83.1,37.0,5.89,30.9,3280,14.00,52.0,5.40,1460

Deuxième dataset : Energie

In [4]:
df2

,name,energy_consumption_btu,world_share,pc_yearly_btu,non_renewable,oil_consump,gas_consump,coal_consump,re_nuclear,co2_emissions_tons_2016,...,oil_reserves,oil_production,oil_consumption,oil_imports,oil_exports,oil_net_imports,oil_year,oil_units,oil_net_exports,oil_daily_deficit/surplus
0,Singapore,3.630377e+12,0.62338%,636011.0,100%,86%,13%,0%,0%,48381759.0,...,0.000000e+00,42274.0,1357000.0,1056958.0,27033.0,1029925.0,2016.0,Barrels,NaN,-1314726.0
1,Poland,4.334474e+12,0.74429%,114206.0,99%,30%,16%,53%,1%,296659670.0,...,1.377520e+08,53367.0,582161.0,494777.0,4490.0,490287.0,2016.0,Barrels,NaN,-528794.0
2,Argentina,3.867524e+12,0.66410%,88024.0,87%,40%,47%,1%,13%,200708270.0,...,2.379702e+09,708770.0,709000.0,16180.0,53930.0,NaN,2016.0,Barrels,37750.0,-230.0
3,Netherlands,3.938133e+12,0.67623%,231364.0,95%,50%,35%,10%,5%,163419285.0,...,1.408920e+08,70128.0,937098.0,1090438.0,6585.0,1083853.0,2016.0,Barrels,NaN,-866970.0
4,Kazakhstan,3.574850e+12,0.61385%,197724.0,97%,18%,16%,64%,3%,231919540.0,...,3.000000e+10,1698280.0,325000.0,469.0,1245575.0,NaN,2016.0,Barrels,1245106.0,1373280.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,Antigua and Barbuda,1.060528e+10,0.00182%,111136.0,97%,97%,0%,0%,3%,438763.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,South Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4038496.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,Palau,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41732.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30262.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,Saint Helena,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13128.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Troisième dataset : Population

In [5]:
df3

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

Quatrième dataset : Armée

In [6]:
df4

,country,country_code,Active Personnel,Aircraft Carriers,Armored Vehicles,Attack Helicopters,Available Manpower,Coastline Coverage,Corvettes,Dedicated Attack,...,Square Land Area,Submarines,Tanker Fleet,Tanks,Total Aircraft Strength,Total Population,Towed Artillery,Trainers,Transports,Waterways (usable)
0,Afghanistan,AFG,0,0,530,0,14611901,0,0,0,...,652230,0,0,0,0,37466414,60,0,0,1200
1,Albania,ALB,8000,0,76,0,1513309,362,0,0,...,28748,0,0,0,19,3088385,0,0,0,41
2,Algeria,ALG,130000,0,6461,45,20916812,998,6,22,...,2381741,6,5,2196,552,43576691,450,87,58,0
3,Angola,ANG,107000,0,1210,15,6728529,1600,0,18,...,1246700,0,0,320,299,33642646,585,61,30,1300
4,Argentina,ARG,83000,0,800,0,20180574,4989,9,6,...,2780400,2,2,349,218,45864941,172,70,22,11000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,Venezuela,VEN,137500,0,2534,10,14534577,2800,0,0,...,912050,2,1,300,256,29069153,104,80,50,7100
136,Vietnam,VTN,470000,0,4420,0,53450591,3444,14,0,...,331210,6,0,2044,218,102789598,599,30,9,17702
137,Yemen,YEM,45000,0,300,14,11551712,1906,2,0,...,527968,0,0,200,177,30399243,43,30,8,0
138,Zambia,ZAM,16500,0,226,0,6677236,0,0,0,...,752618,0,0,75,97,19077816,42,51,11,2250
139,Zimbabwe,ZIM,30000,0,318,6,5635395,0,0,0,...,390757,0,0,50,90,14829988,60,38,14,0

## 2/ Nettoyage des données (Data Cleaning)

On remarque une variation dans la dénomination de la colonne "nom de pays" d'un dataframe à un autre. Afin d'assurer la cohérence et la facilité de manipulation des données, nous avons pris la décision de standardiser cette dénomination en renommant toutes les colonnes correspondantes à "country". Cette démarche permettra d'harmoniser les données entre les différentes sources et facilitera les analyses ultérieures.

In [7]:
#Renommer la colonne ayant le nom du pays à "country"
df2 = df2.rename(columns={'name':'country'})
df3 = df3.rename(columns={'Country/Territory':'country'})

In [9]:
#comparer les pays de df2 et df3
df2 = df2.sort_values('country')
print(df2['country'].unique())
print(df3['country'].unique())

['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Anguilla'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba' 'Australia' 'Austria'
 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus'
 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'British Virgin Islands'
 'Brunei ' 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cabo Verde' 'Cambodia'
 'Cameroon' 'Canada' 'Cayman Islands' 'Central African Republic' 'Chad'
 'Chile' 'China' 'Colombia' 'Comoros' 'Congo' 'Cook Islands' 'Costa Rica'
 'Croatia' 'Cuba' 'Cyprus' 'Czech Republic (Czechia)' "Côte d'Ivoire"
 'DR Congo' 'Denmark' 'Djibouti' 'Dominica' 'Dominican Republic' 'Ecuador'
 'Egypt' 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Faeroe Islands' 'Falkland Islands' 'Fiji' 'Finland' 'France'
 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia' 'Georgia' 'Germany'
 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe' 'Guam'
 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Honduras'
 'Hong Kong' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq'
 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan'
 'Kenya' 'Kiribati' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon'
 'Lesotho' 'Liberia' 'Libya' 'Lithuania' 'Luxembourg' 'Macao' 'Madagascar'
 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Martinique' 'Mauritania'
 'Mauritius' 'Mexico' 'Moldova' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nepal' 'Netherlands' 'New Caledonia'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'North Korea'
 'North Macedonia' 'Norway' 'Oman' 'Pakistan' 'Palau' 'Panama'
 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal'
 'Puerto Rico' 'Qatar' 'Romania' 'Russia' 'Rwanda' 'Réunion'
 'Saint Helena' 'Saint Kitts & Nevis' 'Saint Lucia'
 'Saint Pierre & Miquelon' 'Samoa' 'Sao Tome & Principe' 'Saudi Arabia'
 'Senegal' 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia'
 'Slovenia' 'Solomon Islands' 'Somalia' 'South Africa' 'South Korea'
 'South Sudan' 'Spain' 'Sri Lanka' 'St. Vincent & Grenadines'
 'State of Palestine' 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria'
 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand' 'Timor-Leste' 'Togo' 'Tonga'
 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan'
 'Turks and Caicos' 'U.S. Virgin Islands' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Venezuela' 'Vietnam' 'Western Sahara' 'Yemen'
 'Zambia' 'Zimbabwe']
['Afghanistan' 'Albania' 'Algeria' 'American Samoa' 'Andorra' 'Angola'
 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan'
 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'British Virgin Islands' 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi'
 'Cambodia' 'Cameroon' 'Canada' 'Cape Verde' 'Cayman Islands'
 'Central African Republic' 'Chad' 'Chile' 'China' 'Colombia' 'Comoros'
 'Cook Islands' 'Costa Rica' 'Croatia' 'Cuba' 'Curacao' 'Cyprus'
 'Czech Republic' 'Denmark' 'Djibouti' 'Dominica' 'Dominican Republic'
 'DR Congo' 'Ecuador' 'Egypt' 'El Salvador' 'Equatorial Guinea' 'Eritrea'
 'Estonia' 'Eswatini' 'Ethiopia' 'Falkland Islands' 'Faroe Islands' 'Fiji'
 'Finland' 'France' 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia'
 'Georgia' 'Germany' 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada'
 'Guadeloupe' 'Guam' 'Guatemala' 'Guernsey' 'Guinea' 'Guinea-Bissau'
 'Guyana' 'Haiti' 'Honduras' 'Hong Kong' 'Hungary' 'Iceland' 'India'
 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Isle of Man' 'Israel' 'Italy'
 'Ivory Coast' 'Jamaica' 'Japan' 'Jersey' 'Jordan' 'Kazakhstan' 'Kenya'
 'Kiribati' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg' 'Macau'
 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Marshall Islands' 'Martinique' 'Mauritania' 'Mauritius' 'Mayotte'
 'Mexico' 'Micronesia' 'Moldova' 'Monaco' 'Mongolia' 'Montenegro'
 'Montserrat' 'Morocco' 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal'
 'Netherlands' 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria'
 'Niue' 'North Korea' 'North Macedonia' 'Northern Mariana Islands'
 'Norway' 'Oman' 'Pakistan' 'Palau' 'Palestine' 'Panama'
 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal'
 'Puerto Rico' 'Qatar' 'Republic of the Congo' 'Reunion' 'Romania'
 'Russia' 'Rwanda' 'Saint Barthelemy' 'Saint Kitts and Nevis'
 'Saint Lucia' 'Saint Martin' 'Saint Pierre and Miquelon'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino'
 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia' 'Seychelles'
 'Sierra Leone' 'Singapore' 'Sint Maarten' 'Slovakia' 'Slovenia'
 'Solomon Islands' 'Somalia' 'South Africa' 'South Korea' 'South Sudan'
 'Spain' 'Sri Lanka' 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria'
 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand' 'Timor-Leste' 'Togo'
 'Tokelau' 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan'
 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'United States Virgin Islands' 'Uruguay' 'Uzbekistan' 'Vanuatu'
 'Vatican City' 'Venezuela' 'Vietnam' 'Wallis and Futuna' 'Western Sahara'
 'Yemen' 'Zambia' 'Zimbabwe']

On remarque une variation dans la dénomination des pays dans df2 et df3 donc on doit les renommer de la meme manière.

In [36]:
#On écrit les pays de la même façon

df2['country'] = df2['country'].replace({'Cabo Verde':'Cape Verde','Congo':'Republic of the Congo','Czech Republic (Czechia)':'Czech Republic','Faeroe Islands':'Faroe Islands',"Côte d'Ivoire":"Ivory Coast",'Saint Vincent and the Grenadines':'St. Vincent & Grenadines','State of Palestine':'Palestine','North Macedonia':'Macedonia'})
df3['country'] = df3['country'].replace({'American Samoa':'Samoa','DR Congo':'Congo, Dem. Rep.','Macau':'Macao','Turks and Caicos Islands':'Turks and Caicos','United States Virgin Islands':'U.S. Virgin Islands','North Macedonia':'Macedonia'})

 On fait la même chose pour df1 et df4

In [37]:
#comparer les pays de df2 et df3

print(df4['country'].unique())
print(df3['country'].unique())

['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Armenia'
 'Australia' 'Austria' 'Azerbaijan' 'Bahrain' 'Bangladesh' 'Belarus'
 'Belgium' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'Bulgaria' 'Burkina Faso' 'Cambodia' 'Cameroon' 'Canada'
 'Central African Republic' 'Chad' 'Chile' 'China' 'Colombia' 'Croatia'
 'Cuba' 'Czechia' 'Democratic Republic of the Congo' 'Denmark'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'Eritrea' 'Estonia'
 'Ethiopia' 'Finland' 'France' 'Gabon' 'Georgia' 'Germany' 'Ghana'
 'Greece' 'Guatemala' 'Honduras' 'Hungary' 'India' 'Indonesia' 'Iran'
 'Iraq' 'Ireland' 'Israel' 'Italy' 'Ivory Coast' 'Japan' 'Jordan'
 'Kazakhstan' 'Kenya' 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia'
 'Lebanon' 'Liberia' 'Libya' 'Lithuania' 'Madagascar' 'Malaysia' 'Mali'
 'Mauritania' 'Mexico' 'Moldova' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nepal' 'Netherlands' 'New Zealand'
 'Nicaragua' 'Niger' 'Nigeria' 'North Korea' 'North Macedonia' 'Norway'
 'Oman' 'Pakistan' 'Panama' 'Paraguay' 'Peru' 'Philippines' 'Poland'
 'Portugal' 'Qatar' 'Republic of the Congo' 'Romania' 'Russia'
 'Saudi Arabia' 'Serbia' 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia'
 'Somalia' 'South Africa' 'South Korea' 'South Sudan' 'Spain' 'Sri Lanka'
 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Taiwan' 'Tajikistan'
 'Tanzania' 'Thailand' 'Tunisia' 'Turkey' 'Turkmenistan' 'Uganda'
 'Ukraine' 'United Arab Emirates' 'United Kingdom' 'United States'
 'Uruguay' 'Uzbekistan' 'Venezuela' 'Vietnam' 'Yemen' 'Zambia' 'Zimbabwe']
['Afghanistan' 'Albania' 'Algeria' 'Samoa' 'Andorra' 'Angola' 'Anguilla'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba' 'Australia' 'Austria'
 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus'
 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'British Virgin Islands'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon'
 'Canada' 'Cape Verde' 'Cayman Islands' 'Central African Republic' 'Chad'
 'Chile' 'China' 'Colombia' 'Comoros' 'Cook Islands' 'Costa Rica'
 'Croatia' 'Cuba' 'Curacao' 'Cyprus' 'Czech Republic' 'Denmark' 'Djibouti'
 'Dominica' 'Dominican Republic' 'Congo, Dem. Rep.' 'Ecuador' 'Egypt'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Falkland Islands' 'Faroe Islands' 'Fiji' 'Finland' 'France'
 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia' 'Georgia' 'Germany'
 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe' 'Guam'
 'Guatemala' 'Guernsey' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'Honduras' 'Hong Kong' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran'
 'Iraq' 'Ireland' 'Isle of Man' 'Israel' 'Italy' 'Ivory Coast' 'Jamaica'
 'Japan' 'Jersey' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati' 'Kuwait'
 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon' 'Lesotho' 'Liberia' 'Libya'
 'Liechtenstein' 'Lithuania' 'Luxembourg' 'Macao' 'Madagascar' 'Malawi'
 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Marshall Islands' 'Martinique'
 'Mauritania' 'Mauritius' 'Mayotte' 'Mexico' 'Micronesia' 'Moldova'
 'Monaco' 'Mongolia' 'Montenegro' 'Montserrat' 'Morocco' 'Mozambique'
 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands' 'New Caledonia'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'Niue' 'North Korea'
 'Macedonia' 'Northern Mariana Islands' 'Norway' 'Oman' 'Pakistan' 'Palau'
 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines'
 'Poland' 'Portugal' 'Puerto Rico' 'Qatar' 'Republic of the Congo'
 'Reunion' 'Romania' 'Russia' 'Rwanda' 'Saint Barthelemy'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Martin'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra Leone' 'Singapore' 'Sint Maarten' 'Slovakia'
 'Slovenia' 'Solomon Islands' 'Somalia' 'South Africa' 'South Korea'
 'South Sudan' 'Spain' 'Sri Lanka' 'Sudan' 'Suriname' 'Sweden'
 'Switzerland' 'Syria' 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand'
 'Timor-Leste' 'Togo' 'Tokelau' 'Tonga' 'Trinidad and Tobago' 'Tunisia'
 'Turkey' 'Turkmenistan' 'Turks and Caicos' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'U.S. Virgin Islands' 'Uruguay' 'Uzbekistan' 'Vanuatu' 'Vatican City'
 'Venezuela' 'Vietnam' 'Wallis and Futuna' 'Western Sahara' 'Yemen'
 'Zambia' 'Zimbabwe']

In [10]:
#On écrit les pays de la même façon
df1['country'] = df1['country'].replace({"Cote d'Ivoire":"Ivory Coast",'Kyrgyz Republic':'Kyrgyzstan','Macedonia, FYR':'Macedonia','Congo, Rep.':'Republic of the Congo','Slovak Republic':'Slovakia'})
df4['country'] = df4['country'].replace({'Czechia': 'Czech Republic','Democratic Republic of the Congo':'Congo, Dem. Rep.','North Macedonia':'Macedonia','South Sudan':'Sudan'})

# 3/ Concaténation des datasets

Nous allons combiner df1 (Données générales sur les pays ) aved df4 (Armée) en un dataset merge_23 puis combiner df2 (Energie) avec df3(Population) en un dataset merge_14 en se basant sur la colonne "country"

In [12]:
merge_23 = pd.merge(df2, df3, on='country')
merge_14 = pd.merge(df1, df4, on='country')

In [40]:
merge_23

,country,energy_consumption_btu,world_share,pc_yearly_btu,non_renewable,oil_consump,gas_consump,coal_consump,re_nuclear,co2_emissions_tons_2016,co2_emiss_one_year_change,population_2016,co2_emiss_per_capita,country_share_of_world_co2,coal_reserves,coal_production,coal_consumption,coal_imports,coal_exports,coal_net_imports,coal_year,coal_units,coal_net_exports,coal_yearly_deficit/surplus,gas_reserves,gas_production,gas_consumption,gas_imports,gas_exports,gas_net_imports,gas_year,gas_units,gas_net_exports,gas_yearly_deficit/surplus,oil_reserves,oil_production,oil_consumption,oil_imports,oil_exports,oil_net_imports,oil_year,oil_units,oil_net_exports,oil_daily_deficit/surplus,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,1.446944e+11,0.0248%,3986.0,83%,47%,4%,32%,17%,9900004.0,7.13%,35383032.0,0.28,0.03%,7.275246e+07,1871722.0,1871722.0,0.0,0.0,NaN,2016.0,Tons,0.0,0.0,1750000.0,6675.0,5163.0,0.0,0.0,NaN,2015.0,Million Cubic Ft,0.0,1512.0,0.000000e+00,0.0,35000.0,0.0,0.0,NaN,2016.0,Barrels,0.0,-35000.0,36,AFG,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,Albania,1.118435e+11,0.0192%,38778.0,56%,52%,2%,2%,44%,5208319.0,4.45%,2886438.0,1.80,0.01%,5.754058e+08,0.0,95901.0,89287.0,0.0,89287.0,2016.0,Tons,NaN,-95901.0,29000.0,1236.0,1236.0,0.0,0.0,NaN,2015.0,Million Cubic Ft,0.0,0.0,1.683320e+08,22818.0,27000.0,0.0,18200.0,NaN,2016.0,Barrels,18200.0,-4182.0,138,ALB,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,Algeria,2.398448e+12,0.41184%,57949.0,99%,35%,65%,0%,1%,156220560.0,0.17%,40551392.0,3.85,0.44%,6.503629e+07,0.0,27321.0,27321.0,0.0,27321.0,2016.0,Tons,NaN,-27321.0,159054000.0,6491745.0,1399216.0,0.0,1533342.0,NaN,2015.0,Million Cubic Ft,1533342.0,5092529.0,1.220000e+10,1698786.0,429000.0,139.0,633800.0,NaN,2016.0,Barrels,633661.0,1269786.0,34,DZA,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,Angola,3.628031e+11,0.0623%,12168.0,80%,72%,8%,0%,20%,30566933.0,3.13%,28842489.0,1.06,0.09%,0.000000e+00,0.0,0.0,0.0,0.0,NaN,2016.0,Tons,NaN,0.0,9711000.0,372255.0,27298.0,0.0,0.0,NaN,2015.0,Million Cubic Ft,0.0,344957.0,8.423000e+09,1796743.0,133000.0,0.0,1681354.0,NaN,2016.0,Barrels,1681354.0,1663743.0,42,AGO,Luanda,Africa,35588987,33428485,28127721,23364185,16394062,11828638,8330047,6029700,1246700,28.5466,1.0315,0.45
4,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30262.0,1.52%,14429.0,2.10,0.00%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224,AIA,The Valley,North America,15857,15585,14525,13172,11047,8316,6560,6283,91,174.2527,1.0066,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,Vietnam,3.242514e+12,0.55678%,34276.0,80%,28%,9%,43%,20%,206042140.0,0.09%,93640422.0,2.20,0.58%,3.703762e+09,42468697.0,56641097.0,14693792.0,1546342.0,13147450.0,2016.0,Tons,NaN,-14172400.0,24700000.0,365157.0,320660.0,0.0,0.0,NaN,2015.0,Million Cubic Ft,0.0,44497.0,4.400000e+09,313633.0,478000.0,8712.0,157615.0,NaN,2016.0,Barrels,148903.0,-164367.0,16,VNM,Hanoi,Asia,98186856,96648685,92191398,87411012,79001142,66912613,52968270,41928849,331212,296.4472,1.0074,1.23
201,Western Sahara,3.022000e+09,0.00052%,5469.0,100%,100%,0%,0%,0%,207592.0,2.61%,538749.0,0.39,0.00%,0.000000e+00,0.0,0.0,0.0,0.0,NaN,2016.0,Tons,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2015.0,Million Cubic Ft,NaN,0.0,0.000000e+00,0.0,1701.0,0.0,0.0,NaN,2016.0,Barrels,0.0,-1701.0,172,ESH,El Aaiún,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
202,Yemen,1.384968e+11,0.0238%,4976.0,99%,79%,14%,6%,1%,25647990.0,1.62%,27168208.0,0.94,0.07%,0.000000e+00,0.0,133380.0,153994.0,0.0,153994.0,2016.0,Tons,NaN,-133380.0,16900000.0,444969.0,28605.0,0.0,66745.0,NaN,2015.0,Million Cubic Ft,66745.0,416364.0,3.000000e+09,21960.0,60000.0,0.0,8875.0,NaN,2016.0,Barrels,8875.0,-38040.0,46,YEM,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
203,Zambia,1.779777e+11,0.0306%,10560.0,38%,35%,0%,3%,62%,4230584.0,3.67%,16363458.0,0.26,0.01%,4.960395e+07,138946.0,183693.0,46205.0,1821.0,44384.0,2016.0,Tons,NaN,-44747.0,0.0,0.0,0.0,0.0,0.0,NaN,2015.0,Million Cubic Ft,NaN,0.0,0.000000e+00,170.0,22000.0,10250.0,0.0,10250.0,2016.0,Barrels,NaN,-21830.0,63,ZMB,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
204,Zimbabwe,1.584538e+11,0.0272%,11130.0,73%,32%,0%,41%,27%,10062628.0,-4.17%,14030331.0,0.72,0.03%,5.533596e+08,2976237.0,3388555.0,173.0,47903.0,NaN,2016.0,Tons,47729.0,-412318.0,0.0,0.0,0.0,0.0,0.0,NaN,2015.0,Million Cubic Ft,NaN,0.0,0.000000e+00,819.0,24000.0,0.0,0.0,NaN,2016.0,Barrels,0.0,-23181.0,74,ZWE,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [41]:
merge_14

,country,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp,country_code,Active Personnel,Aircraft Carriers,Armored Vehicles,Attack Helicopters,Available Manpower,Coastline Coverage,Corvettes,Dedicated Attack,Defense Budget,Destroyers,External Debt,Fighters/Interceptors,Fit-for-Service,Foreign Exchange/Gold,Frigates,Helicopter Carriers,Helicopters,Labor Force,Merchant Marine Fleet,Mine Warfare,Navy Ships,Oil Consumption,Oil Production,Oil Proven Reserves,Paramilitary,Patrol Vessels,Ports / Trade Terminals,Purchasing Power Parity,Railway Coverage,Reaching Mil Age Annually,Reserve Personnel,Roadway Coverage,Rocket Projectors,Self-Propelled Artillery,Shared Borders,Special-Mission,Square Land Area,Submarines,Tanker Fleet,Tanks,Total Aircraft Strength,Total Population,Towed Artillery,Trainers,Transports,Waterways (usable)
0,Afghanistan,90.2,10.0,7.58,44.9,1610,9.44,56.2,5.82,553,AFG,0,0,530,0,14611901,0,0,0,99050000,0,284000000,0,8242611,5000000000,0,0,0,8478000,0,0,0,35000,0,0,60000,0,2,36000000000,0,786795,0,34903,13,0,5987,0,652230,0,0,0,0,37466414,60,0,0,1200
1,Albania,16.6,28.0,6.55,48.6,9930,4.49,76.3,1.65,4090,ALB,8000,0,76,0,1513309,362,0,0,192400000,0,9311000000,19,1284768,400000000,0,0,19,1104000,70,0,19,29000,14000,168300000,500,19,4,38000000000,677,61768,0,3945,0,0,691,0,28748,0,0,0,19,3088385,0,0,0,41
2,Algeria,27.3,38.4,4.17,31.4,12900,16.10,76.5,2.89,4460,ALG,130000,0,6461,45,20916812,998,6,22,9700000000,0,5574000000,552,17779290,100000000000,5,0,268,10859000,114,0,201,405000,1260000,12200000000,200000,25,12,470000000000,3973,697227,135000,104000,334,545,6734,9,2381741,6,5,2196,552,43576691,450,87,58,0
3,Angola,119.0,62.3,2.85,42.9,5900,22.40,60.1,6.16,3530,ANG,107000,0,1210,15,6728529,1600,0,18,1059270000,0,42080000000,299,3364265,16995000000,0,0,117,12510000,54,2,40,130000,1600000,9523000000,10000,37,6,205700000000,2852,336426,0,26000,118,28,5369,2,1246700,0,0,320,299,33642646,585,61,30,1300
4,Argentina,14.5,18.9,8.10,16.0,18700,20.90,75.8,2.37,10300,ARG,83000,0,800,0,20180574,4989,9,6,3064800000,4,278524000000,218,17153488,45000000000,0,0,85,18000000,202,0,47,806000,490000,2162000000,20000,13,10,900000000000,36917,687974,0,281290,26,75,11968,10,2780400,2,2,349,218,45864941,172,70,22,11000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,Uzbekistan,36.3,31.7,5.81,28.5,4240,16.50,68.8,2.34,1380,UZB,55000,0,1215,33,16038254,420,0,20,692520000,0,16900000000,200,13478302,16000000000,0,0,96,13273000,0,0,0,60000,41000,594000000,10000,0,1,239420000000,4642,616856,0,86496,98,137,6893,0,447400,0,0,420,200,30842796,60,7,18,1100
124,Venezuela,17.1,28.5,4.91,17.6,16500,45.90,75.4,2.47,13500,VEN,137500,0,2534,10,14534577,2800,0,0,1929600000,0,100300000000,256,11918353,9661000000,2,0,78,14210000,281,0,46,659000,1500000,302300000000,1600000,31,5,265000000000,447,581383,30000,96189,54,60,5267,3,912050,2,1,300,256,29069153,104,80,50,7100
125,Vietnam,23.3,72.0,6.84,80.2,4490,12.10,73.1,1.95,1310,VTN,470000,0,4420,0,53450591,3444,14,0,6237600000,0,96580000000,218,43788369,49500000000,9,0,99,54659000,1926,8,109,438000,245000,4400000000,40000,54,8,800000000000,2600,1747423,0,195468,760,50,4616,4,331210,6,0,2044,218,102789598,599,30,9,17702
126,Yemen,56.3,30.0,5.18,34.4,4480,23.60,67.5,4.67,1310,YEM,45000,0,300,14,11551712,1906,2,0,1010070000,0,6805000000,177,8542187,245400000,0,0,61,7425000,34,3,35,104000,61000,3000000000,375000,15,3,65000000000,0,577586,0,71300,50,10,1601,2,527968,0,0,200,177,30399243,43,30,8,0
127,Zambia,83.1,37.0,5.89,30.9,3280,14.00,52.0,5.40,1460,ZAM,16500,0,226,0,6677236,0,0,0,251160000,0,11660000000,97,3796485,2082000000,0,0,27,6898000,2,0,0,23000,0,0,1000,0,1,60120000000,3126,343401,0,67671,50,0,6043,0,752618,0,0,75,97,19077816,42,51,11,2250

Maintenant on veut voir les pays qui ne figurent pas à la fois dans merge_23 et merge_14

In [42]:
#On crée une liste pour chaque dataframe (merge_23 et merge_14)
l23=[]
l14 = []
for c in merge_23['country']:
    l23.append(c)
for c in merge_14['country']:
    l14.append(c)

#On écrit les pays qui ne sont pas présents dans les deux df
for c in l23:
    if c not in l14:
        print(c)
print('##################')
for c in l14:
    if c not in l23:
        print(c)

Anguilla
Antigua and Barbuda
Aruba
Bahamas
Barbados
Belize
Benin
Bermuda
British Virgin Islands
Burundi
Cape Verde
Cayman Islands
Comoros
Cook Islands
Costa Rica
Cuba
Cyprus
Djibouti
Dominica
Equatorial Guinea
Eswatini
Ethiopia
Faroe Islands
Falkland Islands
Fiji
French Guiana
French Polynesia
Gambia
Gibraltar
Greenland
Grenada
Guadeloupe
Guam
Guinea
Guinea-Bissau
Guyana
Haiti
Honduras
Hong Kong
Iceland
Jamaica
Kiribati
Laos
Lesotho
Luxembourg
Macao
Malawi
Maldives
Malta
Martinique
Mauritius
Mexico
New Caledonia
Nicaragua
North Korea
Palau
Papua New Guinea
Puerto Rico
Rwanda
Saint Lucia
Samoa
Samoa
Senegal
Seychelles
Solomon Islands
Somalia
South Sudan
Palestine
Syria
Taiwan
Timor-Leste
Togo
Tonga
Trinidad and Tobago
Turks and Caicos
U.S. Virgin Islands
Vanuatu
Western Sahara
Zimbabwe
##################
Congo, Dem. Rep.

# 4/ Dataset Final

Finalement, on a les 4 datasets originaux dans un seul dataframe 'merge'

In [33]:
#On fusionne merge_14 et merge_23
pd.set_option('display.max_columns', None)
merge = pd.merge(merge_14, merge_23, on='country')
merge

,country,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp,country_code,Active Personnel,Aircraft Carriers,Armored Vehicles,Attack Helicopters,Available Manpower,Coastline Coverage,Corvettes,Dedicated Attack,Defense Budget,Destroyers,External Debt,Fighters/Interceptors,Fit-for-Service,Foreign Exchange/Gold,Frigates,Helicopter Carriers,Helicopters,Labor Force,Merchant Marine Fleet,Mine Warfare,Navy Ships,Oil Consumption,Oil Production,Oil Proven Reserves,Paramilitary,Patrol Vessels,Ports / Trade Terminals,Purchasing Power Parity,Railway Coverage,Reaching Mil Age Annually,Reserve Personnel,Roadway Coverage,Rocket Projectors,Self-Propelled Artillery,Shared Borders,Special-Mission,Square Land Area,Submarines,Tanker Fleet,Tanks,Total Aircraft Strength,Total Population,Towed Artillery,Trainers,Transports,Waterways (usable),energy_consumption_btu,world_share,pc_yearly_btu,non_renewable,oil_consump,gas_consump,coal_consump,re_nuclear,co2_emissions_tons_2016,co2_emiss_one_year_change,population_2016,co2_emiss_per_capita,country_share_of_world_co2,coal_reserves,coal_production,coal_consumption,coal_imports,coal_exports,coal_net_imports,coal_year,coal_units,coal_net_exports,coal_yearly_deficit/surplus,gas_reserves,gas_production,gas_consumption,gas_imports,gas_exports,gas_net_imports,gas_year,gas_units,gas_net_exports,gas_yearly_deficit/surplus,oil_reserves,oil_production,oil_consumption,oil_imports,oil_exports,oil_net_imports,oil_year,oil_units,oil_net_exports,oil_daily_deficit/surplus,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,90.2,10.0,7.58,44.9,1610,9.44,56.2,5.82,553,AFG,0,0,530,0,14611901,0,0,0,99050000,0,284000000,0,8242611,5000000000,0,0,0,8478000,0,0,0,35000,0,0,60000,0,2,36000000000,0,786795,0,34903,13,0,5987,0,652230,0,0,0,0,37466414,60,0,0,1200,1.446944e+11,0.0248%,3986.0,83%,47%,4%,32%,17%,9900004.0,7.13%,35383032.0,0.28,0.03%,7.275246e+07,1871722.0,1871722.0,0.0,0.0,NaN,2016.0,Tons,0.0,0.0,1750000.0,6675.0,5163.0,0.0,0.0,NaN,2015.0,Million Cubic Ft,0.0,1512.0,0.000000e+00,0.0,35000.0,0.0,0.0,NaN,2016.0,Barrels,0.0,-35000.0,36,AFG,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,Albania,16.6,28.0,6.55,48.6,9930,4.49,76.3,1.65,4090,ALB,8000,0,76,0,1513309,362,0,0,192400000,0,9311000000,19,1284768,400000000,0,0,19,1104000,70,0,19,29000,14000,168300000,500,19,4,38000000000,677,61768,0,3945,0,0,691,0,28748,0,0,0,19,3088385,0,0,0,41,1.118435e+11,0.0192%,38778.0,56%,52%,2%,2%,44%,5208319.0,4.45%,2886438.0,1.80,0.01%,5.754058e+08,0.0,95901.0,89287.0,0.0,89287.0,2016.0,Tons,NaN,-95901.0,29000.0,1236.0,1236.0,0.0,0.0,NaN,2015.0,Million Cubic Ft,0.0,0.0,1.683320e+08,22818.0,27000.0,0.0,18200.0,NaN,2016.0,Barrels,18200.0,-4182.0,138,ALB,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,Algeria,27.3,38.4,4.17,31.4,12900,16.10,76.5,2.89,4460,ALG,130000,0,6461,45,20916812,998,6,22,9700000000,0,5574000000,552,17779290,100000000000,5,0,268,10859000,114,0,201,405000,1260000,12200000000,200000,25,12,470000000000,3973,697227,135000,104000,334,545,6734,9,2381741,6,5,2196,552,43576691,450,87,58,0,2.398448e+12,0.41184%,57949.0,99%,35%,65%,0%,1%,156220560.0,0.17%,40551392.0,3.85,0.44%,6.503629e+07,0.0,27321.0,27321.0,0.0,27321.0,2016.0,Tons,NaN,-27321.0,159054000.0,6491745.0,1399216.0,0.0,1533342.0,NaN,2015.0,Million Cubic Ft,1533342.0,5092529.0,1.220000e+10,1698786.0,429000.0,139.0,633800.0,NaN,2016.0,Barrels,633661.0,1269786.0,34,DZA,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,Angola,119.0,62.3,2.85,42.9,5900,22.40,60.1,6.16,3530,ANG,107000,0,1210,15,6728529,1600,0,18,1059270000,0,42080000000,299,3364265,16995000000,0,0,117,12510000,54,2,40,130000,1600000,9523000000,10000,37,6,205700000000,2852,336426,0,26000,118,28,5369,2,1246700,0,0,320,299,33642646,585,61,30,1300,3.628031e+11,0.0623%,12168.0,80%,72%,8%,0%,20%,30566933.0,3.13%,28842489.0,1.06,0.09%,0.000000e+00,0.0,0.0,0.0,0.0,NaN,2016.0,Tons,NaN,0.0,9711000.0,372255.0,27298.0,0.0,0.0,NaN,2015.0,Million Cubic Ft,0.0,344957.0,8.423000e+09,1796743.0,133000.0,0.0,1681354.0,NaN,2016.0,Barrels,1681354.0,1663743.0,42,AGO,Luanda,Africa,35588987,33428485,28127721,23364185,16394062,11828638,8330047,6029700,1246700,28.5466,1.0315,0.45
4,Argentina,14.5,18.9,8.10,16.0,18700,20.90,75.8,2.37,10300,ARG,83000,0,800,0,20180574,4989,9,6,3064800000,4,278524000000,218,17153488,45000000000,0,0,85,18000000,202,0,47,806000,490000,2162000000,20000,13,10,900000000000,36917,687974,0,281290,26,75,11968,10,2780400,2,2,349,218,45864941,172,70,22,11000,3.867524e+12,0.66410%,88024.0,87%,40%,47%,1%,13%,200708270.0,0.16%,43508460.0,4.61,0.56%,5.511550e+08,29318.0,1403477.0,1729270.0,1235.0,1728035.0,2016.0,Tons,NaN,-1374159.0,11142000.0,1518545.0,1659452.0,376811.0,2825.0,373986.0,2015.0,Million Cubic Ft,NaN,-140907.0,2.379702e+09,708770.0,709000.0,16180.0,53930.0,NaN,2016.0,Barrels,37750.0,-230.0,33,ARG,Buenos Aires,South America,45510318,45036032,43257065,41100123,37070774,32637657,28024803,23842803,2780400,16.3683,1.0052,0.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,Uzbekistan,36.3,31.7,5.81,28.5,4240,16.50,68.8,2.34,1380,UZB,55000,0,1215,33,16038254,420,0,20,692520000,0,16900000000,200,13478302,16000000000,0,0,96,13273000,0,0,0,60000,41000,594000000,10000,0,1,239420000000,4642,616856,0,86496,98,137,6893,0,447400,0,0,420,200,30842796,60,7,18,1100,1.798255e+12,0.30878%,56266.0,96%,6%,86%,4%,4%,109347340.0,1.60%,31441751.0,3.48,0.31%,1.515676e+09,4793946.0,4770798.0,49605.0,60.0,49545.0,2016.0,Tons,NaN,23149.0,65000000.0,2037676.0,1700417.0,0.0,266628.0,NaN,2015.0,Million Cubic Ft,266628.0,337258.0,5.940000e+08,71471.0,49000.0,3678.0,0.0,3678.0,2016.0,Barrels,NaN,22471.0,43,UZB,Tashkent,Asia,34627652,33526656,30949417,28614227,24925554,20579100,15947129,12011361,447400,77.3975,1.0160,0.43
119,Venezuela,17.1,28.5,4.91,17.6,16500,45.90,75.4,2.47,13500,VEN,137500,0,2534,10,14534577,2800,0,0,1929600000,0,100300000000,256,11918353,9661000000,2,0,78,14210000,281,0,46,659000,1500000,302300000000,1600000,31,5,265000000000,447,581383,30000,96189,54,60,5267,3,912050,2,1,300,256,29069153,104,80,50,7100,2.492569e+12,0.42801%,84774.0,76%,39%,37%,0%,24%,175884256.0,-1.90%,29851255.0,5.89,0.49%,8.057886e+08,825630.0,180696.0,36935.0,639340.0,NaN,2016.0,Tons,602404.0,644934.0,197087000.0,2832122.0,935953.0,17658.0,0.0,17658.0,2015.0,Million Cubic Ft,NaN,1896168.0,2.999530e+11,2355424.0,598000.0,0.0,1725049.0,NaN,2016.0,Barrels,1725049.0,1757424.0,51,VEN,Caracas,South America,28301696,28490453,30529716,28715022,24427729,19750579,15210443,11355475,916445,30.8820,1.0036,0.35
120,Vietnam,23.3,72.0,6.84,80.2,4490,12.10,73.1,1.95,1310,VTN,470000,0,4420,0,53450591,3444,14,0,6237600000,0,96580000000,218,43788369,49500000000,9,0,99,54659000,1926,8,109,438000,245000,4400000000,40000,54,8,800000000000,2600,1747423,0,195468,760,50,4616,4,331210,6,0,2044,218,102789598,599,30,9,17702,3.242514e+12,0.55678%,34276.0,80%,28%,9%,43%,20%,206042140.0,0.09%,93640422.0,2.20,0.58%,3.703762e+09,42468697.0,56641097.0,14693792.0,1546342.0,13147450.0,2016.0,Tons,NaN,-14172400.0,24700000.0,365157.0,320660.0,0.0,0.0,NaN,2015.0,Million Cubic Ft,0.0,44497.0,4.400000e+09,313633.0,478000.0,8712.0,157615.0,NaN,2016.0,Barrels,148903.0,-164367.0,16,VNM,Hanoi,Asia,98186856,96648685,92191398,87411012,79001142,66912613,52968270,41928849,331212,296.4472,1.0074,1.23
121,Yemen,56.3,30.0,5.18,34.4,4480,23.60,67.5,4.67,1310,YEM,45000,0,300,14,11551712,1906,2,0,1010070000,0,6805000000,177,8542187,245400000,0,0,61,7425000,34,3,35,104000,61000,3000000000,375000,15,3,65000000000,0,577586,0,71300,50,10,1601,2,527968,0,0,200,177,30399243,43,30,8,0,1.384968e+11,0.0238%,4976.0,99%,79%,14%,6%,1%,25647990.0,1.62%,27168208.0,0.94,0.07%,0.000000e+00,0.0,133380.0,153994.0,0.0,153994.0,2016.0,Tons,NaN,-133380.0,16900000.0,444969.0,28605.0,0.0,66745.0,NaN,2015.0,Million Cubic Ft,66745.0,416364.0,3.000000e+09,21960.0,60000.0,0.0,8875.0,NaN,2016.0,Barrels,8875.0,-38040.0,46,YEM,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
122,Zambia,83.1,37.0,5.89,30.9,3280,14.00,52.0,5.40,1460,ZAM,16500,0,226,0,6677236,0,0,0,251160000,0,11660000000,97,3796485,2082000000,0,0,27,6898000,2,0,0,23000,0,0,1000,0,1,60120000000,3126,343401,0,67671,50,0,6043,0,752618,0,0,75,97,19077816,42,51,11,2250,1.779777e+11,0.0306%,10560.0,38%,35%,0%,3%,62%,4230584.0,3.67%,16363458.0,0.26,0.01%,4.960395e+07,138946.0,183693.0,46205.0,1821.0,44384.0,2016.0,Tons,NaN,-44747.0,0.0,0.0,0.0,0.0,0.0,NaN,2015.0,Million Cubic Ft,NaN,0.0,0.000000e+00,170.0,22000.0,10250.0,0.0,10250.0,2016.0,Barrels,NaN,-21830.0,63,ZMB,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25

On enlève les colonnes qui sont inutiles ou redondantes

In [34]:
#Notre dataframe est nommé 'df' désormais
df = merge.drop(['population_2016','Rank','CCA3','Capital','Continent','2020 Population','2015 Population','2010 Population','2000 Population','1990 Population','1980 Population','1970 Population','Density (per km²)','World Population Percentage','country_code','gas_units','coal_units','oil_units','oil_year','coal_year'], axis=1)

In [35]:
#On enlève la colonne "country" 
#X contient maintenant la colonne "country"
#df contient les variables de décision
X = df.pop('country')

Quelles colonnes contiennent des valeurs nulles ?

In [24]:
for i in range(95):
    if df[df.columns[i]].isnull().any() == True:
        print(df.columns[i])
df

coal_net_imports
coal_net_exports
gas_reserves
gas_production
gas_consumption
gas_imports
gas_exports
gas_net_imports
gas_year
gas_net_exports
gas_yearly_deficit/surplus
oil_net_imports
oil_net_exports

,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp,Active Personnel,Aircraft Carriers,Armored Vehicles,Attack Helicopters,Available Manpower,Coastline Coverage,Corvettes,Dedicated Attack,Defense Budget,Destroyers,External Debt,Fighters/Interceptors,Fit-for-Service,Foreign Exchange/Gold,Frigates,Helicopter Carriers,Helicopters,Labor Force,Merchant Marine Fleet,Mine Warfare,Navy Ships,Oil Consumption,Oil Production,Oil Proven Reserves,Paramilitary,Patrol Vessels,Ports / Trade Terminals,Purchasing Power Parity,Railway Coverage,Reaching Mil Age Annually,Reserve Personnel,Roadway Coverage,Rocket Projectors,Self-Propelled Artillery,Shared Borders,Special-Mission,Square Land Area,Submarines,Tanker Fleet,Tanks,Total Aircraft Strength,Total Population,Towed Artillery,Trainers,Transports,Waterways (usable),energy_consumption_btu,world_share,pc_yearly_btu,non_renewable,oil_consump,gas_consump,coal_consump,re_nuclear,co2_emissions_tons_2016,co2_emiss_one_year_change,co2_emiss_per_capita,country_share_of_world_co2,coal_reserves,coal_production,coal_consumption,coal_imports,coal_exports,coal_net_imports,coal_net_exports,coal_yearly_deficit/surplus,gas_reserves,gas_production,gas_consumption,gas_imports,gas_exports,gas_net_imports,gas_year,gas_net_exports,gas_yearly_deficit/surplus,oil_reserves,oil_production,oil_consumption,oil_imports,oil_exports,oil_net_imports,oil_net_exports,oil_daily_deficit/surplus,2022 Population,Area (km²),Growth Rate
0,90.2,10.0,7.58,44.9,1610,9.44,56.2,5.82,553,0,0,530,0,14611901,0,0,0,99050000,0,284000000,0,8242611,5000000000,0,0,0,8478000,0,0,0,35000,0,0,60000,0,2,36000000000,0,786795,0,34903,13,0,5987,0,652230,0,0,0,0,37466414,60,0,0,1200,1.446944e+11,0.0248%,3986.0,83%,47%,4%,32%,17%,9900004.0,7.13%,0.28,0.03%,7.275246e+07,1871722.0,1871722.0,0.0,0.0,NaN,0.0,0.0,1750000.0,6675.0,5163.0,0.0,0.0,NaN,2015.0,0.0,1512.0,0.000000e+00,0.0,35000.0,0.0,0.0,NaN,0.0,-35000.0,41128771,652230,1.0257
1,16.6,28.0,6.55,48.6,9930,4.49,76.3,1.65,4090,8000,0,76,0,1513309,362,0,0,192400000,0,9311000000,19,1284768,400000000,0,0,19,1104000,70,0,19,29000,14000,168300000,500,19,4,38000000000,677,61768,0,3945,0,0,691,0,28748,0,0,0,19,3088385,0,0,0,41,1.118435e+11,0.0192%,38778.0,56%,52%,2%,2%,44%,5208319.0,4.45%,1.80,0.01%,5.754058e+08,0.0,95901.0,89287.0,0.0,89287.0,NaN,-95901.0,29000.0,1236.0,1236.0,0.0,0.0,NaN,2015.0,0.0,0.0,1.683320e+08,22818.0,27000.0,0.0,18200.0,NaN,18200.0,-4182.0,2842321,28748,0.9957
2,27.3,38.4,4.17,31.4,12900,16.10,76.5,2.89,4460,130000,0,6461,45,20916812,998,6,22,9700000000,0,5574000000,552,17779290,100000000000,5,0,268,10859000,114,0,201,405000,1260000,12200000000,200000,25,12,470000000000,3973,697227,135000,104000,334,545,6734,9,2381741,6,5,2196,552,43576691,450,87,58,0,2.398448e+12,0.41184%,57949.0,99%,35%,65%,0%,1%,156220560.0,0.17%,3.85,0.44%,6.503629e+07,0.0,27321.0,27321.0,0.0,27321.0,NaN,-27321.0,159054000.0,6491745.0,1399216.0,0.0,1533342.0,NaN,2015.0,1533342.0,5092529.0,1.220000e+10,1698786.0,429000.0,139.0,633800.0,NaN,633661.0,1269786.0,44903225,2381741,1.0164
3,119.0,62.3,2.85,42.9,5900,22.40,60.1,6.16,3530,107000,0,1210,15,6728529,1600,0,18,1059270000,0,42080000000,299,3364265,16995000000,0,0,117,12510000,54,2,40,130000,1600000,9523000000,10000,37,6,205700000000,2852,336426,0,26000,118,28,5369,2,1246700,0,0,320,299,33642646,585,61,30,1300,3.628031e+11,0.0623%,12168.0,80%,72%,8%,0%,20%,30566933.0,3.13%,1.06,0.09%,0.000000e+00,0.0,0.0,0.0,0.0,NaN,NaN,0.0,9711000.0,372255.0,27298.0,0.0,0.0,NaN,2015.0,0.0,344957.0,8.423000e+09,1796743.0,133000.0,0.0,1681354.0,NaN,1681354.0,1663743.0,35588987,1246700,1.0315
4,14.5,18.9,8.10,16.0,18700,20.90,75.8,2.37,10300,83000,0,800,0,20180574,4989,9,6,3064800000,4,278524000000,218,17153488,45000000000,0,0,85,18000000,202,0,47,806000,490000,2162000000,20000,13,10,900000000000,36917,687974,0,281290,26,75,11968,10,2780400,2,2,349,218,45864941,172,70,22,11000,3.867524e+12,0.66410%,88024.0,87%,40%,47%,1%,13%,200708270.0,0.16%,4.61,0.56%,5.511550e+08,29318.0,1403477.0,1729270.0,1235.0,1728035.0,NaN,-1374159.0,11142000.0,1518545.0,1659452.0,376811.0,2825.0,373986.0,2015.0,NaN,-140907.0,2.379702e+09,708770.0,709000.0,16180.0,53930.0,NaN,37750.0,-230.0,45510318,2780400,1.0052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,36.3,31.7,5.81,28.5,4240,16.50,68.8,2.34,1380,55000,0,1215,33,16038254,420,0,20,692520000,0,16900000000,200,13478302,16000000000,0,0,96,13273000,0,0,0,60000,41000,594000000,10000,0,1,239420000000,4642,616856,0,86496,98,137,6893,0,447400,0,0,420,200,30842796,60,7,18,1100,1.798255e+12,0.30878%,56266.0,96%,6%,86%,4%,4%,109347340.0,1.60%,3.48,0.31%,1.515676e+09,4793946.0,4770798.0,49605.0,60.0,49545.0,NaN,23149.0,65000000.0,2037676.0,1700417.0,0.0,266628.0,NaN,2015.0,266628.0,337258.0,5.940000e+08,71471.0,49000.0,3678.0,0.0,3678.0,NaN,22471.0,34627652,447400,1.0160
119,17.1,28.5,4.91,17.6,16500,45.90,75.4,2.47,13500,137500,0,2534,10,14534577,2800,0,0,1929600000,0,100300000000,256,11918353,9661000000,2,0,78,14210000,281,0,46,659000,1500000,302300000000,1600000,31,5,265000000000,447,581383,30000,96189,54,60,5267,3,912050,2,1,300,256,29069153,104,80,50,7100,2.492569e+12,0.42801%,84774.0,76%,39%,37%,0%,24%,175884256.0,-1.90%,5.89,0.49%,8.057886e+08,825630.0,180696.0,36935.0,639340.0,NaN,602404.0,644934.0,197087000.0,2832122.0,935953.0,17658.0,0.0,17658.0,2015.0,NaN,1896168.0,2.999530e+11,2355424.0,598000.0,0.0,1725049.0,NaN,1725049.0,1757424.0,28301696,916445,1.0036
120,23.3,72.0,6.84,80.2,4490,12.10,73.1,1.95,1310,470000,0,4420,0,53450591,3444,14,0,6237600000,0,96580000000,218,43788369,49500000000,9,0,99,54659000,1926,8,109,438000,245000,4400000000,40000,54,8,800000000000,2600,1747423,0,195468,760,50,4616,4,331210,6,0,2044,218,102789598,599,30,9,17702,3.242514e+12,0.55678%,34276.0,80%,28%,9%,43%,20%,206042140.0,0.09%,2.20,0.58%,3.703762e+09,42468697.0,56641097.0,14693792.0,1546342.0,13147450.0,NaN,-14172400.0,24700000.0,365157.0,320660.0,0.0,0.0,NaN,2015.0,0.0,44497.0,4.400000e+09,313633.0,478000.0,8712.0,157615.0,NaN,148903.0,-164367.0,98186856,331212,1.0074
121,56.3,30.0,5.18,34.4,4480,23.60,67.5,4.67,1310,45000,0,300,14,11551712,1906,2,0,1010070000,0,6805000000,177,8542187,245400000,0,0,61,7425000,34,3,35,104000,61000,3000000000,375000,15,3,65000000000,0,577586,0,71300,50,10,1601,2,527968,0,0,200,177,30399243,43,30,8,0,1.384968e+11,0.0238%,4976.0,99%,79%,14%,6%,1%,25647990.0,1.62%,0.94,0.07%,0.000000e+00,0.0,133380.0,153994.0,0.0,153994.0,NaN,-133380.0,16900000.0,444969.0,28605.0,0.0,66745.0,NaN,2015.0,66745.0,416364.0,3.000000e+09,21960.0,60000.0,0.0,8875.0,NaN,8875.0,-38040.0,33696614,527968,1.0217
122,83.1,37.0,5.89,30.9,3280,14.00,52.0,5.40,1460,16500,0,226,0,6677236,0,0,0,251160000,0,11660000000,97,3796485,2082000000,0,0,27,6898000,2,0,0,23000,0,0,1000,0,1,60120000000,3126,343401,0,67671,50,0,6043,0,752618,0,0,75,97,19077816,42,51,11,2250,1.779777e+11,0.0306%,10560.0,38%,35%,0%,3%,62%,4230584.0,3.67%,0.26,0.01%,4.960395e+07,138946.0,183693.0,46205.0,1821.0,44384.0,NaN,-44747.0,0.0,0.0,0.0,0.0,0.0,NaN,2015.0,NaN,0.0,0.000000e+00,170.0,22000.0,10250.0,0.0,10250.0,NaN,-21830.0,20017675,752612,1.0280

On remarque que les valeurs nulles signifient 0  (aucun exports de gas naturel etc...) donc on les remplace par la valeur  numérique 0 .

In [36]:
df = df.fillna(0)

On convertit les valeurs en "%" en valeurs numériques réelles.

In [37]:
cols = ['world_share','gas_consump','non_renewable','oil_consump','coal_consump','re_nuclear','co2_emiss_one_year_change','country_share_of_world_co2']
for col in cols:
    df[col] = df[col].str.replace('%', '').astype(float) / 100

Normalisation des données avec StandardScaler()

In [38]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data_scaled = scaler.fit_transform(df)

Corrélation entre les variables

In [70]:
df.corr()

,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp,Active Personnel,Aircraft Carriers,Armored Vehicles,Attack Helicopters,Available Manpower,Coastline Coverage,Corvettes,Dedicated Attack,Defense Budget,Destroyers,External Debt,Fighters/Interceptors,Fit-for-Service,Foreign Exchange/Gold,Frigates,Helicopter Carriers,Helicopters,Labor Force,Merchant Marine Fleet,Mine Warfare,Navy Ships,Oil Consumption,Oil Production,Oil Proven Reserves,Paramilitary,Patrol Vessels,Ports / Trade Terminals,Purchasing Power Parity,Railway Coverage,Reaching Mil Age Annually,Reserve Personnel,Roadway Coverage,Rocket Projectors,Self-Propelled Artillery,Shared Borders,Special-Mission,Square Land Area,Submarines,Tanker Fleet,Tanks,Total Aircraft Strength,Total Population,Towed Artillery,Trainers,Transports,Waterways (usable),energy_consumption_btu,world_share,pc_yearly_btu,non_renewable,oil_consump,gas_consump,coal_consump,re_nuclear,co2_emissions_tons_2016,co2_emiss_one_year_change,co2_emiss_per_capita,country_share_of_world_co2,coal_reserves,coal_production,coal_consumption,coal_imports,coal_exports,coal_net_imports,coal_net_exports,coal_yearly_deficit/surplus,gas_reserves,gas_production,gas_consumption,gas_imports,gas_exports,gas_net_imports,gas_year,gas_net_exports,gas_yearly_deficit/surplus,oil_reserves,oil_production,oil_consumption,oil_imports,oil_exports,oil_net_imports,oil_net_exports,oil_daily_deficit/surplus,2022 Population,Area (km²),Growth Rate
child_mort,1.000000,-0.302884,-0.310677,-0.175624,-0.553428,0.325698,-0.876638,0.906721,-0.506398,-0.083155,-0.056302,-0.195066,-0.131589,0.015217,-0.141025,-0.136155,-0.114034,-0.131233,-0.122228,-0.218531,-0.133408,0.003762,-0.151829,-0.233477,-0.142382,-0.132410,-0.009737,-0.133421,-0.255211,-0.216566,-0.167532,-0.126072,-0.110661,0.038323,-0.069604,-0.317615,-0.143586,-0.150789,0.061558,-0.109201,-0.107048,-0.103718,-0.153892,0.181124,-0.120436,-0.063310,-0.167814,-0.079783,-0.118797,-0.133408,0.029196,-0.093174,-0.131655,-0.122106,-0.087096,-0.140860,-0.141067,-0.463455,0.083558,0.459297,-0.234309,-0.198762,-0.083558,-0.112935,0.172827,-0.489143,-0.112874,-0.123649,-0.071846,-0.067713,-0.120595,-0.083724,-0.106428,-0.073588,0.022602,-0.093076,-0.134983,-0.173705,-0.284293,-0.148269,-0.253126,-0.065031,-0.103231,-0.000556,-0.111724,-0.135451,-0.165352,-0.169557,-0.081076,-0.158741,-0.063968,0.042615,0.033132,-0.056971,0.545583
exports,-0.302884,1.000000,-0.104983,0.761979,0.451243,-0.125868,0.280521,-0.274195,0.304902,-0.212124,-0.075544,-0.113599,-0.138186,-0.163544,-0.112200,-0.063218,-0.143002,-0.122918,-0.158383,-0.058718,-0.156147,-0.159674,-0.027639,-0.116443,-0.157216,-0.146528,-0.146986,0.041990,-0.074738,-0.183189,-0.123276,-0.058329,-0.003319,-0.142348,-0.134049,-0.161593,-0.154761,-0.176712,-0.179832,-0.154289,-0.195441,-0.126060,-0.086474,-0.258078,-0.150900,-0.207001,-0.158374,-0.097513,-0.145724,-0.156147,-0.175341,-0.133578,-0.174257,-0.177079,-0.160381,-0.125048,-0.125134,0.500550,0.111224,-0.062402,0.194462,-0.061764,-0.111224,-0.120951,-0.005477,0.343962,-0.120918,-0.160030,-0.105326,-0.088021,-0.085873,-0.122698,-0.091565,-0.127482,-0.020101,-0.026933,-0.099523,-0.123992,-0.070077,0.016390,-0.073059,0.055232,0.024840,-0.009126,-0.004382,-0.066928,-0.123847,-0.082001,0.032248,-0.074751,0.043837,0.077400,-0.174929,-0.210128,-0.095593
health,-0.310677,-0.104983,1.000000,0.085674,0.220002,-0.304975,0.353027,-0.309286,0.451183,-0.017417,-0.120800,0.176888,0.254442,-0.087846,0.153373,-0.081810,0.166689,0.334700,0.317817,0.514533,0.293473,-0.083787,0.015147,0.041881,0.365019,0.314200,-0.068708,0.060933,0.086908,0.006639,0.282586,0.060135,-0.090887,-0.159659,-0.210725,0.324048,0.209309,0.350127,-0.118420,-0.013871,0.243268,-0.077553,-0.028342,-0.120689,0.357072,0.087735,0.161998,0.355479,-0.010442,0.293473,-0.085109,-0.111992,0.306339,0.257040,-0.001918,0.170407,0.171164,0.066197,-0.251724,-0.072658,-0.210479,0.109986,0.251724,0.100077,-0.325392,0.060698,0.099985,0.207180,-0.001080,0.003383,0.021922,0.000630,0.002888,-0.012894,-0.020492,-0.133313,0.169601,0.257683,0.373048,0.009273,0.257597,0.096394,-0.120142,-0.083510,-0.090817,0.094726,0.279304,0.269635,-0.124422,0.249342,-0.158777,-0.248611,-0.086867,0.079617,-0.174470
imports,-0.175624,0.761979,0.085674,1.000000,0.111008,-0.230251,0.129506,-0.170571,0.050661,-0.287720,-0.065692,-0.210610,-0.203164,-0.208545,-0.160546,-0.158874,-0.215087,-0.171746,-0.198834,-0.115885,-0.218169,-0.204956,-0.117075,-0.210858,-0.190008,-0.199909,-0.191600,0.033552,-0.180125,-0.322787,-0.203121,-0.240872,-0.183167,-0.163528,-0.288465,-0.321077,-0.225111,-0.234190,-0.216582,-0.209556,-0.250625,-0.210799,-0.163802,-0.348989,-0.191934,-0.300222,-0.242476,-0.115640,-0.212657,-0.218169,-0.217918,-0.216909,-0.236827,-0.245684,-0.244105,-0.198102,-0.198186,0.187665,-0.029342,0.055364,-0.094849,0.023703,0.029342,-0.185437,0.125740,0.047284,-0.185474,-0.214651,-0.150686,-0.128651,-0.142597,-0.169878,-0.142472,-0.170610,-0.015871,-0.202572,-0.235523,-0.224791,-0.145815,-0.182156,-0.132881,-0.001588,-0.171121,-0.168189,-0.184475,-0.241275,-0.203134,-0.137318,-0.182083,-0.126937,-0.168063,-0.046288,-0.217136,-0.305115,-0.020556
income,-0.553428,0.451243,0.220002,0.111008,1.000000,-0.220940,0.638277,-0.485705,0.889149,-0.017315,-0.045566,0.186208,0.163315,-0.085554,0.154858,0.058617,0.113361,0.190229,0.155769,0.341938,0.174593,-0.079456,0.106229,0.114852,0.190866,0.175871,-0.067190,0.099635,0.163707,0.124034,0.196674,0.265150,0.212041,-0.107012,0.022301,0.318662,0.122913,0.168510,-0.117091,-0.001532,0.101439,-0.018114,0.052415,-0.220417,0.179048,0.061413,0.120436,0.165420,0.016504,0.174593,-0.089258,-0.012547,0.189268,0.135399,-0.021017,0.114601,0.114930,0.891691,0.036335,-0.207642,0.291435,-0.085069,-0.036335,0.061780,-0.241417,0.789339,0.061875,0.116130,-0.010860,-0.014823,0.041818,0.063718,0.026720,0.053688,0.025134,0.253431,0.254297,0.228999,0.303934,0.419312,0.230210,0.080304,0.366735,0.210876,0.213007,0.278840,0.191160,0.175877,0.251922,0.159942,0.231242,0.111785,-0.091413,0.054621,-0.270636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
oil_net_exports,-0.063968,0.043837,-0.158777,-0.168063,0.231242,0.299778,0.037125,0.007980,0.091408,0.136711,-0.028269,0.235667,0.210665,0.004077,0.197363,0.326053,0.313787,0.086061,0.005272,-0.052145,0.136303,0.000213,0.101662,0.081256,-0.056559,0.114069,-0.004000,0.030188,0.225050,0.197664,0.133715,0.791963,0.780188,0.019393,0.163952,0.035996,0.032913,0.088542,-0.008924,0.009658,0.022013,0.336690,0.377158,0.270247,0.055681,0.389145,0.211253,0.009921,0.344440,0.136303,0.001037,0.470205,0.094647,0.180814,0.251955,0.097550,0.097400,0.312379,0.162873,0.011991,0.207994,-0.121414,-0.162873,0.060470,-0.159039,0.328388,0.060514,0.149513,0.002092,-0.023326,-0.050711,0.096088,-0.073873,0.082250,0.119094,0.560980,0.389895,0.301305,-0.033283,0.394058,-0.087575,0.028211,0.396470,0.429687,0.780206,0.739509,0.134652,-0.084091,0.992787,-0.092950,1.000000,0.794227,0.000659,0.389969,0.011025
oil_daily_deficit/surplus,0.042615,0.077400,-0.248611,-0.046288,0.111785,0.273024,-0.094844,0.119865,-0.034779,-0.369755,-0.009924,-0.241237,-0.158795,-0.462518,0.079046,-0.040825,-0.054784,-0.314932,-0.449486,-0.371927,-0.261794,-0.470315,-0.400098,-0.354488,-0.403148,-0.255536,-0.487394,-0.289364,-0.109246,-0.222047,-0.389674,0.433065,0.565970,-0.065686,-0.061428,-0.379123,-0.521957,-0.340319,-0.433587,-0.247636,-0.472752,-0.020687,0.061004,-0.014863,-0.309792,0.086067,-0.261112,-0.244969,0.031381,-0.261794,-0.459859,0.214311,-0.272790,-0.210541,-0.123008,-0.448327,-0.448405,0.179198,0.077481,0.075896,0.211717,-0.295845,-0.077481,-0.479406,-0.028913,0.191725,-0.479383,-0.234172,-0.467308,-0.507634,-0.543424,0.038380,-0.557356,0.036769,0.465148,0.457743,0.123047,-0.068097,-0.464839,0.337944,-0.489762,0.002009,0.411713,0.484125,0.566498,0.359893,-0.393345,-0.636576,0.772208,-0.646872,0.794227,1.000000,-0.456022,0.089412,0.089628
2022 Population,0.033132,-0.174929,-0.086867,-0.217136,-0.091413,0.070265,-0.028398,-0.047214,-0.080033,0.856108,-0.015923,0.562334,0.333270,0.995348,0.101929,0.600476,0.427088,0.382092,0.451515,0.180188,0.402935,0.993307,0.695568,0.655035,0.199290,0.343979,0.978868,0.430835,0.363616,0.612071,0.594429,0.239426,0.033721,0.347179,0.429455,0.372656,0.771961,0.515071,0.993882,0.606448,0.785662,0.599018,0.387236,0.571056,0.304969,0.420631,0.605682,0.148678,0.480951,0.402935,0.999598,0.393536,0.335027,0.467130,0.612512,0.744521,0.743687,-0.057525,0.102602,-0.156610,-0.040995,0.363911,-0.102602,0.805931,-0.011361,-0.031914,0.805966,0.549360,0.806725,0.821542,0.790371,0.092449,0.784735,0.079206,-0.543599,0.113304,0.220478,0.316054,0.321493,0.040111,0.329626,0.013867,0.008147,-0.068138,0.034394,0.264578,0.601822,0.725278,0.014656,0.735450,0.000659,-0.456022,1.000000,0.423015,-0.049170
Area (km²),-0.056971,-0.210128,0.079617,-0.305115,0.054621,0.065385,0.032065,-0.070646,0.074614,0.587497,-0.033496,0.640482,0.658770,0.431611,0.511810,0.727983,0.768610,0.547519,0.494328,0.329479,0.580281,0.428235,0.411035,0.430051,0.356834,0.537552,0.446697,0.307237,0.535189,0.588796,0.606924,0.698645,0.281719,0.063675,0.180389,0.453942,0.578575,0.692591,0.381552,0.401939,0.622009,0.660934,0.680180,0.762741,0.491588,0.998682,0.742186,0.354247,0.687476,0.580281,0.427632,0.595182,0.499501,0.672259,0.778882,0.630223,0.630149,0.159364,0.058570,-0.136738,0.061625,0.159132,-0.058570,0.572440,-0.235722,0.188197,0.572460,0.765926,0.512460,0.438754,0.281754,0.438785,0.235336,0.409817,0.048143,0.557404,0.704932,0.689744,0.254868,0.581842,0.117335,0.015590,0.505355,0.467232,0.285460,0.685991,0.609110,0.431290,0.441051,0.394127,0.389969,0.089412,0.423015,1.000000,-0.043375
Growth Rate,0.545583,-0.095593,-0.174470,-0.020556,-0.270636,0.188110,-0.486617,0.602230,-0.242691,-0.132384,-0.042452,-0.222421,-0.111744,-0.063989,-0.071262,-0.121524,-0.121311,-0.093936,-0.109210,-0.129505,-0.105403,-0.067465,-0.126786,-0.188031,-0.093477,-0.101294,-0.074967,-0.116205,-0.183391,-0.189217,-0.123114,-0.047714,-0.018280,-0.016677,-0.099259,-0.222019,-0.128411,-0.132713,-0.031663,-0.165835,-0.109490,-0.149217,-0.190080,0.051842,-0.088984,-0.048545,-0.148625,-0.042939,-0.176332,-0.105403,-0.054323,-0.218833,-0.098321,-0.103369,-0.112434,-0.127031,-0.126986,-0.230269,0.101825,0.310478,-0.082483,-0.180435,-0.101825,-0.114473,0.078793,-0.274103,-0.114405,-0.139246,-0.082889,-0.087322,-0.158737,-0.042931,-0.152311,-0.036988,0.069628,-0.080836,-0.085085,-0.134063,-0.241685,-0.090562,-0.239273,-0.081505,-0.066100,0.052124,-0.019357,-0.056876,-0.123088,-0.145031,0.004028,-0.143449,0.011025,0.089628,-0.049170,-0.043375,1.000000

# 5/PCA

On remarque que notre dataframe contient un grand nombre de colonnes, soit un total de 95 colonnes. La gestion de tant de variables peut être complexe et peut entraîner des problèmes de dimensionnalité. Afin de simplifier et de réduire la complexité de nos données, nous avons pris la décision d'utiliser l'analyse en composantes principales (PCA).

In [39]:
from sklearn.decomposition import PCA

# Après des tests on a choisit 15 composants
pca = PCA(n_components=15)
principal_components = pca.fit_transform(data_scaled)

principal_df = pd.DataFrame(data = principal_components, columns = ['PC1', 'PC2','PC3','PC4','PC5','PC6', 'PC7','PC8','PC9','PC10','PC11', 'PC12','PC13','PC14','PC15'])

principal_df

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15
0,-2.559254,1.214814,-0.429437,3.358889,-0.116552,0.084732,0.287395,-0.026359,-0.904773,0.403934,-0.815149,-0.212156,1.583238,-0.387109,-0.394421
1,-2.643774,0.502667,0.971883,0.132246,-0.636869,-1.010308,1.345144,-0.488879,0.885481,-0.968147,0.722698,-0.085778,0.091086,-0.134610,0.107188
2,0.785231,-2.658877,-2.336811,0.265739,-0.246431,-0.298550,-1.448489,-0.301484,0.596740,2.169518,-0.061565,-0.958434,-1.064799,0.591475,-0.216208
3,-1.822054,-0.545345,-1.903953,3.229424,1.736357,0.529756,0.366985,0.235848,-1.582005,0.207423,0.943994,0.975069,0.179762,-1.072098,-0.354131
4,-0.124166,-0.246996,-0.053172,0.231328,-0.143905,0.217988,0.494638,0.686330,0.795950,0.992849,-1.300384,-1.389441,-0.838816,0.519291,-0.577571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,-1.599746,-0.262672,-0.527056,0.661069,0.135659,-0.368384,-1.576766,-0.189829,1.071779,1.415418,-1.709269,-2.104330,-0.580321,-0.810754,-0.355931
119,-0.326906,-3.293119,-3.438330,-0.388751,5.434171,2.462592,2.344441,0.981074,3.237638,-1.028137,-0.304400,-1.381265,-0.388393,-1.319586,-0.003389
120,0.342366,1.496035,-1.091625,-0.588872,-0.941577,-1.124969,-0.741861,-0.329128,0.160184,-2.041947,-0.357668,0.477447,0.264922,-0.511779,-0.220525
121,-2.298473,0.516522,-0.506210,2.319834,0.560496,0.651151,-0.948918,0.578568,-0.921937,0.497684,0.045676,-0.289711,-0.514384,0.513645,-0.203002
122,-2.652676,0.889485,-0.096619,3.273026,-0.370923,-1.019096,2.680065,-0.905163,-0.230780,0.868270,0.438713,0.126772,0.810468,-1.801657,-0.181803

In [40]:

# Output de l'ACP, variance expliquée par axe, variance expliquée en %,
# variance cumulée en % pour les 'p' axes de vecteurs directeurs les vecteurs propres 
eig = pd.DataFrame(
    {   "Dimension" : ["Dim" + str(x) for x in range(1,16)], 
        "Varianceexpliquée" : pca.explained_variance_,
        "%variance_expliquée" : np.round(pca.explained_variance_ratio_ * 100),
        "cumvarexpliquée" : np.round(np.cumsum(pca.explained_variance_ratio_) * 100)
    }
)

eig

   Dimension  Varianceexpliquée  %variance_expliquée  cumvarexpliquée
0       Dim1          38.276596                 40.0             40.0
1       Dim2          11.350581                 12.0             52.0
2       Dim3           8.206988                  9.0             60.0
3       Dim4           6.299155                  7.0             67.0
4       Dim5           3.768285                  4.0             71.0
5       Dim6           2.895741                  3.0             74.0
6       Dim7           2.609529                  3.0             77.0
7       Dim8           2.409804                  3.0             79.0
8       Dim9           2.218263                  2.0             81.0
9      Dim10           1.807574                  2.0             83.0
10     Dim11           1.448487                  2.0             85.0
11     Dim12           1.353848                  1.0             86.0
12     Dim13           1.211221                  1.0             88.0
13     Dim14           1.141855                  1.0             89.0
14     Dim15           1.020557                  1.0             90.0

Ainsi, on a pu obtenir un dataframe avec 15 colonnes au lieu de 95. Ces 15 colonnes expliquent 90% de la variance de nos données !

# 6/ Clustering avec Kmeans

Trouvons tout d'abord le nombre optimal de n_clusters

In [52]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
dict={}
for i in range(2,11):    
    # intialise kmeans
    kmeans = KMeans(n_clusters=i,random_state=42)
    kmeans.fit(principal_df)
    cluster_labels = kmeans.labels_
     
    dict[i]=silhouette_score(principal_df, cluster_labels)
dict

C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

{2: 0.7754543400107952,
 3: 0.7617033951512269,
 4: 0.4069564348973541,
 5: 0.4014712876893217,
 6: 0.428702789545214,
 7: 0.39800567254901487,
 8: 0.19839343935327275,
 9: 0.2160195749583753,
 10: 0.18276497323181345}

On trouve que le nombre optimal est 2 ou 3 (ils donnent les meilleurs silhouette_score). On choisit de fixer n_clusters à 3.

In [53]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


kmeans = KMeans(n_clusters=3,random_state=42)
kmeans.fit(principal_df)

# Le label du cluster pour chaque point
cluster_labels = kmeans.predict(principal_df)

# Ajoutons le label au dataframe
principal_df['cluster'] = cluster_labels

# Le nombre de pays que contient chaque cluster
print(principal_df['cluster'].value_counts())

1    119
2      2
0      2
Name: cluster, dtype: int64
0.7648409530953006

C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [54]:
#On ajoute les pays au dataframes

final =pd.concat([X,principal_df],axis=1)
final

,country,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,cluster
0,Afghanistan,-2.559254,1.214814,-0.429437,3.358889,-0.116552,0.084732,0.287395,-0.026359,-0.904773,0.403934,-0.815149,-0.212156,1.583238,-0.387109,-0.394421,1
1,Albania,-2.643774,0.502667,0.971883,0.132246,-0.636869,-1.010308,1.345144,-0.488879,0.885481,-0.968147,0.722698,-0.085778,0.091086,-0.134610,0.107188,1
2,Algeria,0.785231,-2.658877,-2.336811,0.265739,-0.246431,-0.298550,-1.448489,-0.301484,0.596740,2.169518,-0.061565,-0.958434,-1.064799,0.591475,-0.216208,1
3,Angola,-1.822054,-0.545345,-1.903953,3.229424,1.736357,0.529756,0.366985,0.235848,-1.582005,0.207423,0.943994,0.975069,0.179762,-1.072098,-0.354131,1
4,Argentina,-0.124166,-0.246996,-0.053172,0.231328,-0.143905,0.217988,0.494638,0.686330,0.795950,0.992849,-1.300384,-1.389441,-0.838816,0.519291,-0.577571,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,Uzbekistan,-1.599746,-0.262672,-0.527056,0.661069,0.135659,-0.368384,-1.576766,-0.189829,1.071779,1.415418,-1.709269,-2.104330,-0.580321,-0.810754,-0.355931,1
119,Venezuela,-0.326906,-3.293119,-3.438330,-0.388751,5.434171,2.462592,2.344441,0.981074,3.237638,-1.028137,-0.304400,-1.381265,-0.388393,-1.319586,-0.003389,1
120,Vietnam,0.342366,1.496035,-1.091625,-0.588872,-0.941577,-1.124969,-0.741861,-0.329128,0.160184,-2.041947,-0.357668,0.477447,0.264922,-0.511779,-0.220525,1
121,Yemen,-2.298473,0.516522,-0.506210,2.319834,0.560496,0.651151,-0.948918,0.578568,-0.921937,0.497684,0.045676,-0.289711,-0.514384,0.513645,-0.203002,1
122,Zambia,-2.652676,0.889485,-0.096619,3.273026,-0.370923,-1.019096,2.680065,-0.905163,-0.230780,0.868270,0.438713,0.126772,0.810468,-1.801657,-0.181803,1

In [55]:
# On crée une variable qui contient les pays de chaque cluster
Cluster1Countries=final[final['cluster']==0]
Cluster2Countries=final[final['cluster']==1]
Cluster3Countries=final[final['cluster']==2]

# 7/ Exploration des résultats

In [56]:
# Les pays du premier cluster
Cluster1Countries['country']

90            Russia
116    United States
Name: country, dtype: object

In [57]:
# Les pays du deuxième cluster
Cluster2Countries['country']

0      Afghanistan
1          Albania
2          Algeria
3           Angola
4        Argentina
          ...
118     Uzbekistan
119      Venezuela
120        Vietnam
121          Yemen
122         Zambia
Name: country, Length: 119, dtype: object

In [59]:
# Les pays du troisième cluster
Cluster3Countries['country']

26    China
45    India
Name: country, dtype: object

# 8/ Interprétation des résultats

Dans notre projet de segmentation de pays en utilisant l'algorithme K-means, nous avons obtenu trois clusters distincts. Le premier cluster comprend la Russie et les États-Unis, le deuxième cluster comprend la Chine et l'Inde, tandis que le troisième cluster regroupe tous les autres pays.

Cette segmentation peut être interprétée de la manière suivante : le premier cluster, composé de la Russie et des États-Unis, pourrait représenter les superpuissances mondiales, caractérisées par leur influence politique, économique et militaire significative à l'échelle mondiale.

Le deuxième cluster, qui inclut la Chine et l'Inde, peut être interprété comme regroupant les pays émergents avec de vastes populations et des économies en pleine croissance. Ces pays ont également un rôle de plus en plus important sur la scène internationale.

Enfin, le troisième cluster englobe tous les autres pays, ce qui suggère une segmentation plus diversifiée des pays restants en fonction de leurs caractéristiques socio-économiques, géographiques et politiques spécifiques.